using System;
using UnityEngine;

namespace KitsuMate.Onnx.Tts
{
    /// <summary>
    /// Result of text-to-speech synthesis.
    /// Contains raw audio samples that can be converted to an AudioClip on the main thread.
    /// </summary>
    [Serializable]
    public class TtsResult
    {
        /// <summary>Raw PCM audio samples (mono, float32, normalized to [-1, 1]).</summary>
        public float[] Samples;

        /// <summary>Sample rate of the generated audio in Hz.</summary>
        public int SampleRate;

        /// <summary>Number of speech tokens generated by the model.</summary>
        public int TokensGenerated;

        /// <summary>Duration of the generated audio in seconds.</summary>
        public float Duration => Samples != null && SampleRate > 0
            ? (float)Samples.Length / SampleRate
            : 0f;

        /// <summary>
        /// Creates an AudioClip from the raw samples. Must be called on the main thread.
        /// </summary>
        /// <param name="name">Name for the AudioClip.</param>
        /// <returns>A new AudioClip containing the generated audio.</returns>
        public AudioClip ToAudioClip(string name = "TTS")
        {
            if (Samples == null || Samples.Length == 0)
                return null;

            var clip = AudioClip.Create(name, Samples.Length, 1, SampleRate, false);
            clip.SetData(Samples, 0);
            return clip;
        }
    }
}
